### ISSUE TITLE
Fails if mite project is not associated with a customer

### ISSUE THREAD

**Issue by ghost** [thomasklein/redmine2mite#1]
Hi,

in addition to my commercial projects I track my private projects with mite and don't assign a customer to them. When connecting Redmine with mite I only get the message "Could not update your account data.", after some digging it turned out that the point of failure was one of my mite projects that had no customer associated with itself. The actual error message is this:

```
NoMethodError: undefined method `customer_name' for #<Mite::Project:0xb5e0adfc>
```

As a workaround I associated the project with a customer, which is fine for me.

Best regards,
Lars

**Comment by thomasklein** [comment]
Bug fixed.

Thanks for your feedback Lars!
