### ISSUE TITLE
Cannot update plugin via git

### ISSUE THREAD

**Issue by flo1o1** [thomasklein/redmine2mite#15]
I'm getting an error after trying to update the plugin via "git pull":

fatal: http://github.com/thomasklein/Redmine2mite/info/refs not found: did you run git update-server-info on the server?

**Comment by flo1o1** [comment]
This is how I fixed it:
- Backup your old plugin directory (e. g. tar cfz ~/remin2mite_backup.tar.gz REDMINE_PATH/vendor/plugins/redmine2mite)
- Delete old plugin dir (rm -Rf REDMINE_PATH/vendor/plugins/redmine2mite)
- cd REDMINE_PATH/vendor/plugins/
- Checkout plugin using git: git clone <redmine2mite-git-url>
- gem install json
- cd REDMINE_PATH
- RAILS_ENV=production rake db:migrate_plugins (Change environment variable to fit your needs)
- Restart Apache/Mongrel/whatever

That's it.

**Comment by thomasklein** [comment]
Thx!
