### ISSUE TITLE
Time tracker feature: I don't see a stop watch...

### ISSUE THREAD

**Issue by flo1o1** [thomasklein/redmine2mite#17]
# Preconditions
- Latest redmine2mite version (as of Mar 2012)
- Checked the "Activate tracker functionality, if time entries are booked without effort" option in Mite settings
# Issue

You don't see a stop watch in the "Spent time" view and thus cannot stop the time tracker from within Redmine.
# Solution

Ask your Redmine administrator to change role permissions and grant the "Edit own time logs" permission for your role

**Comment by thomasklein** [comment]
Thx for pointing this out!
