### ISSUE TITLE
Spent time doesn't include time tracker time

### ISSUE THREAD

**Issue by flo1o1** [thomasklein/redmine2mite#20]
This is just a small, confusing issue :) Imagine this situation:

I'm working on an issue, so the time tracker is running. After I'm done, I click on the time tracker status and the "Spent time" view comes up. I can see my issue, but the "Hours" value right besides the stopwatch still says "0:00", see [screenshot](http://imagebin.org/206784) whiche made me think "Huh, was there an error syncing the time to mite??" 

Dunno if there's a way to merge the already spent time with the time tracker time and thus show the correct value for the time spent in total on this task.

**Comment by thomasklein** [comment]
Hi Floeschie!
Thanks for your comment on that. Taking this into the upcoming release!
