### ISSUE TITLE
Compatibility to Redmine 2.0.x broken

### ISSUE THREAD

**Issue by maatien** [thomasklein/redmine2mite#23]
There are incompatibilities to run properly on Redmine 2.0.x.
So, for example, 'dispatcher' doesn't exist anymore in Rails 3 (http://www.redmine.org/issues/11035#note-5).

Also, other parts must be rewritten.

**Comment by thomasklein** [comment]
Hi Maatien,

sorry for my late response, right now I'm totally out of time. For the next version I will open up a  new branch supporting Rails 3 and Redmine 2.0.x. Meanwhile, any helping hands are welcome : )

Cheers,
Thomas

**Comment by jurrack** [comment]
Hi Thomas,

I don't see a new branch, have you canceled this plan?

**Comment by thomasklein** [comment]
Still on it! Trying to get things rolling this weekend.

Am 14.11.2012 um 09:27 schrieb Steffen Jurrack notifications@github.com:

**Comment by thomasklein** [comment]
Updated. Feedback very welcome!

**Comment by dkamenev** [comment]
Thumb Up! It works fine with newest Redmine Version! (2.2.1)

**Comment by thomasklein** [comment]
Great! : )
