### ISSUE TITLE
defaults for mite fields and start/stop button

### ISSUE THREAD

**Issue by ghost** [thomasklein/redmine2mite#3]
Nice little plugin you wrote there. there are just 2 things that imho could be improved:
1. Defaults
   Its annoying to choose the inputfields mite.project and mite.service, every time you create an new mite entry. there should be defaults which can be set  for each project.
2. Start/stopp button
   It would be nice to have a button on the ticket view, which starts a simple time counter. cklicking again redirects to the time input form with the stopped time preinserted.

**Comment by thomasklein** [comment]
Hi kangaroody, thanks for providing feedback on the plugin!

As for your 1. suggestion:
You can at least set the project fixed, if you assign one of your mite projects to one of your redmine projects in the plugin settings (/mite).

Hopefully i'll have time to include your suggestions soon, but right now i'm unfortunately loaded with work.

Thomas

**Comment by thomasklein** [comment]
1. Setting defaults is possible in the plugin's preferences.
2. Time tracker capability is included as of version 1.5
