### ISSUE TITLE
comment field - project identifier marker {project_identifier} missing

### ISSUE THREAD

**Issue by maximilianschmid** [thomasklein/redmine2mite#4]
A project identifier marker {project_identifier} would be very handy for building full URLs within comments that point to certain resources. This would complement the RESTfullness of redmine and make this plugin even more powerfull.

**Comment by thomasklein** [comment]
Hey anorakio!
You can use {project} already. Or do you mean something else?

Cheers,
Thomas

**Comment by thomasklein** [comment]
ok, so i guess this one is closed...
