### ISSUE TITLE
Redmine 2 Mite Connection not working when ...?

### ISSUE THREAD

**Issue by chrishuppert** [thomasklein/redmine2mite#5]
redmine is only installed on localhost? ;-)

**Comment by thomasklein** [comment]
Hey Chris! What do you mean by that?

**Comment by chrishuppert** [comment]
Hey Thomas!
Thank you heartly for your answer :-) I mean by that the following:

If I call redmine on http://localhost/3000 and want to create a connection to mite from redmine then redmine cannot connect to mite. 

And my question is:
Is this because I call it from localhost? So if I would call it from a webserver in the net, then it would work? 

Cheers, 
Christian

**Comment by thomasklein** [comment]
Hey Christian!

No, it should work without problems also on your computer. Do you get any error messages in the console when using Redmine?

Greetings,
Thomas

**Comment by chrishuppert** [comment]
Yes, I get the following error message:

"Could not update your account data."

Cheers, 
Christian

**Comment by thomasklein** [comment]
Hi Chris!
Just in case, firstly please recheck your mite account data (Url and API key) and try it again.
If that didn't work, please have a look into your console window and check the output for any abnormalities (meaning everything else except SQL queries and controller/action status stuff). If there are any, could you please post it here? 

Additionally, please tell me which version of Redmine and which version of Redmine2mite you are using.

Greetings,
Thomas
